// =====================================================================
// RS_ForeignPickups -- OUR MODELS ON THEIR FLOOR PICKUPS.
//
// The other half of RS_ForeignModels. That file paints a donor mesh into
// the player's hands; this one paints the SAME donor onto the same
// weapon lying on the floor, so the thing you walk up to is the thing
// you end up holding.
//
// HOW THE BIND WORKS -- the same two steps as the hand, aimed at the
// world sprite path instead of the HUD one:
//   1. A_ChangeModel(<pickupClass>) sets the item's per-instance
//      modelData->modelDef. The WORLD path resolves models against the
//      actor's model data before its class, exactly as the HUD path does
//      (hw_sprites.cpp HWSprite::Process -> models.cpp
//      FindModelFrame(AActor*)), so no engine work was needed for this.
//   2. Frame lookup still keys on sprite+frame, so the ITEM's sprite is
//      pinned to our anchor -- item.sprite/item.frame rather than
//      psp.Sprite/psp.Frame.
//
// WHY A SECOND SET OF MODELDEF BLOCKS AND NOT THE HUD ONES.
// A HUD block's Scale is tuned for a mesh at arm's length in view space
// and its pose is whatever was comfortable for the hand. On the floor
// that reads as a car-sized gun standing on its muzzle. The MS_PU_*
// blocks are generated by tools_gen_pickups.ps1, which solves Scale,
// Offset and the three rotation offsets from each mesh's own rest-frame
// vertices. See that file for the geometry.
//
// -------------------------------------------------------------------
// THE DISJOINT-ANCHOR INVARIANT. This is the load-bearing idea and the
// reason the rest of this file can be as simple as it is.
//
// Every HUD block anchors on a HAND sprite (PISG, SHTG, CHGG, MISG,
// PLSG, BFGG, PUNG, SAWG, and the donors' own HB**/REVL/RIFL/...).
// Every pickup block anchors on SHOT A, which appears in no HUD shelf
// row. The two sprite spaces do not overlap ANYWHERE.
//
// So a binding that is stale in either direction resolves to NOTHING:
// FindModelFrame returns null and the actor falls back to drawing its
// sprite. A weapon still carrying its HUD modelDef when it lands on the
// floor draws a sprite, not a giant gun. A pickup binding left on a
// weapon that has been picked up cannot affect the hand, because the
// psprite is pinned to a HUD anchor the pickup block has no entry for.
//
// That is what makes the owner transition need no hook at all. There is
// no event for "this weapon was picked up" that a foreign class would
// let us see, and we do not need one: in single player the floor item
// and the carried weapon are the SAME actor (Inventory::CreateCopy
// returns self when GoAway() is false), so the two binders would be
// fighting over one modelData -- except that whichever one is wrong at
// any moment is inert. The hand binder re-points modelDef on selection;
// this one re-points it on the next sweep. In between, a sprite.
//
// EVERY FAILURE MODE IN THIS FILE DEGRADES TO "FLAT SPRITE". None of
// them degrades to a wrong model at a wrong size. Keep it that way.
// -------------------------------------------------------------------
//
// GATED behind rs_foreignmodels (the master switch) and
// rs_foreignmodels_pickups.
// =====================================================================

// ---------------------------------------------------------------------
// The display actor every generated MS_PU_* class derives from.
//
// SAFE TO SUBCLASS, unlike the donor stubs in zscript.txt: those must
// not be subclassed because FindModelFrameRaw's smff->type == ti is an
// exact class-pointer test, so a subclass inherits no model. The test
// still holds here -- it is just satisfied the other way round. This
// base owns NO modeldef block; each generated subclass owns its own, so
// each one matches itself exactly and the shared parent is only carrying
// the state and the flags.
//
// Spawn is the anchor sprite at letter A, which is the same (class,
// sprite, frame) triple the binder pins a real pickup to. That makes any
// MS_PU_* directly spawnable as a display prop that resolves its own
// model with no A_ChangeModel at all -- which is what ms_modelzoo and
// the test map use, so the zoo is showing the exact block the binder
// will use rather than an approximation of it.
// ---------------------------------------------------------------------
class MS_PickupModel : Actor
{
	Default
	{
		+NOBLOCKMAP
		+NOGRAVITY
		+NOINTERACTION
		+DONTSPLASH
		+NOTONAUTOMAP
		Radius 1;
		Height 1;
	}

	States
	{
	Spawn:
		SHOT A -1;
		Stop;
	}
}

// ---------------------------------------------------------------------
// HUD donor class -> pickup class. Generated; paste from
// .gen/pickups.shelf.
//
// A donor with no row here keeps its sprite pickup and is NOT an error:
// the RS_GH_*, RS_PS_* and VR_* rows on the main shelf are RS_Main's
// models, which this pk3 neither ships nor measures. Standalone, the
// shelf drops those rows for want of their donor classes and the
// coverage is complete.
// ---------------------------------------------------------------------
class MS_PickupShelf
{
	// Split at build time, not per lookup. PickupFor runs once per tracked
	// item per sweep; splitting 44 rows into a throwaway array on each call
	// was allocation for nothing.
	Array<string> mHud;
	Array<string> mPick;

	void Build()
	{
		if (mHud.Size() > 0) return;
		static const string PU[] = {
			"MS_Pistol|MS_PU_Pistol",
			"MS_Revolver|MS_PU_Revolver",
			"MS_Chaingun|MS_PU_Chaingun",
			"MS_RocketLauncher|MS_PU_RocketLauncher",
			"MS_Chainsaw|MS_PU_Chainsaw",
			"MS_Fist|MS_PU_Fist",
			"MS_VR_BFG9000|MS_PU_VR_BFG9000",
			"MS_MG_Knife|MS_PU_MG_Knife",
			"MS_MG_Tec9|MS_PU_MG_Tec9",
			"MS_MG_Chaingun|MS_PU_MG_Chaingun",
			"MS_MG_RPG|MS_PU_MG_RPG",
			"MS_MG_Bolter|MS_PU_MG_Bolter",
			"MS_BW_Colt|MS_PU_BW_Colt",
			"MS_BW_Garand|MS_PU_BW_Garand",
			"MS_BW_MG42|MS_PU_BW_MG42",
			"MS_BW_MP40|MS_PU_BW_MP40",
			"MS_BW_Kar98|MS_PU_BW_Kar98",
			"MS_BW_STG44|MS_PU_BW_STG44",
			"MS_BW_Thompson|MS_PU_BW_Thompson",
			"MS_BW_Trenchgun|MS_PU_BW_Trenchgun",
			"MS_Shotgun|MS_PU_Shotgun",
			"MS_SuperShotgun|MS_PU_SuperShotgun",
			"MS_MG_Shotgun|MS_PU_MG_Shotgun",
			"MS_MG_SSG|MS_PU_MG_SSG",
			"MS_BD_AssaultShotgun|MS_PU_BD_AssaultShotgun",
			"MS_BD_nade|MS_PU_BD_nade",
			"MS_BD_Boot|MS_PU_BD_Boot",
			"MS_BD_BFG|MS_PU_BD_BFG",
			"MS_BD_BFG_10k|MS_PU_BD_BFG_10k",
			"MS_BD_BrutalAxe|MS_PU_BD_BrutalAxe",
			"MS_BD_DSweap|MS_PU_BD_DSweap",
			"MS_BD_Flamethrower2|MS_PU_BD_Flamethrower2",
			"MS_BD_M79|MS_PU_BD_M79",
			"MS_BD_Machinegun|MS_PU_BD_Machinegun",
			"MS_BD_Minigun|MS_PU_BD_Minigun",
			"MS_BD_BrutalPistol|MS_PU_BD_BrutalPistol",
			"MS_BD_Plasma|MS_PU_BD_Plasma",
			"MS_BD_RailGun|MS_PU_BD_RailGun",
			"MS_BD_Revolver|MS_PU_BD_Revolver",
			"MS_BD_Rifle|MS_PU_BD_Rifle",
			"MS_BD_Shotgun|MS_PU_BD_Shotgun",
			"MS_BD_BrutalSMG|MS_PU_BD_BrutalSMG",
			"MS_BD_SSG|MS_PU_BD_SSG",
			// No trailing comma: ZScript's initialiser list will not take one.
			"MS_BD_Unmaker|MS_PU_BD_Unmaker"
		};
		for (int i = 0; i < PU.Size(); ++i)
		{
			Array<string> f;
			PU[i].Split(f, "|");
			if (f.Size() != 2) continue;
			mHud.Push(f[0]);
			mPick.Push(f[1]);
		}
	}

	// "" when this donor has no pickup model. Callers must treat that as
	// "leave the item alone", never as a reason to pin anything.
	string PickupFor(string hudCls) const
	{
		for (int i = 0; i < mHud.Size(); ++i)
			if (mHud[i] == hudCls) return mPick[i];
		return "";
	}

	// Every pickup class we know, for the model zoo.
	void AllPickups(out Array<string> outCls) const
	{
		outCls.Clear();
		for (int i = 0; i < mPick.Size(); ++i) outCls.Push(mPick[i]);
	}
}

// One tracked floor item.
class MS_PickupBind
{
	// Weapon, not Actor: Owner is an Inventory field, so a plain Actor
	// pointer cannot answer the one question this whole file turns on --
	// is this thing on the floor or in somebody's hands.
	Weapon item;
	int   origSprite;   // theirs, so the pin can be undone
	int   origFrame;
	string bound;       // pickup class currently on it, "" = not ours
}

// ---------------------------------------------------------------------
// The binder.
//
// Its own handler rather than more code in RS_ForeignModelHandler: this
// runs against world actors on a slow sweep, that one runs against
// psprites every tic, and the only thing they share is the answer to
// "which donor does this weapon wear", which is read through the public
// Get()/FindEntry()/mShelf surface that already exists for the wheel
// bridge. Nothing in RS_ForeignModels.zs had to change.
// ---------------------------------------------------------------------
class MS_PickupHandler : StaticEventHandler
{
	Array<MS_PickupBind> mBinds;
	MS_PickupShelf mPU;

	int  mAnchorSpr;     // sprite index of SHOT, -1 if this IWAD lacks it
	int  mSweep;         // tic counter for the discovery/rebind cadence
	bool mWasEnabled;    // so switching the cvar off can undo the pins

	// Discovery and re-bind cadence. Once a second: a menu pick landing up
	// to a second later is imperceptible, and it keeps the ThinkerIterator
	// off the per-tic path. The sprite pin below still runs every tic,
	// because a mod whose pickup state loops through frames would flicker
	// between its sprite and our model at any slower rate.
	const SWEEP_TICS = 35;

	static bool Enabled()
	{
		CVar m = CVar.FindCVar("rs_foreignmodels");
		if (!m || !m.GetBool()) return false;
		CVar p = CVar.FindCVar("rs_foreignmodels_pickups");
		return (p && p.GetBool());
	}

	static MS_PickupHandler Get()
	{
		return MS_PickupHandler(StaticEventHandler.Find("MS_PickupHandler"));
	}

	override void WorldLoaded(WorldEvent e)
	{
		// Fires on savegame restore too, which is what rebuilds the tracked
		// list: this handler is static, so its arrays do not come back with
		// the save, but every binding on the items themselves does --
		// modelData is serialised (AActor::Serialize, "modelData"), as is
		// the pinned sprite. A restored item is already correct; the sweep
		// is only re-learning which items to keep an eye on.
		mBinds.Clear();
		if (!mPU) { mPU = new("MS_PickupShelf"); mPU.Build(); }

		// GetSpriteIndex returns -1 for a name that was never registered,
		// and FindModelFrameRaw indexes sprites[] with it unchecked --
		// (unsigned)-1 is an out-of-bounds read, not a missing model. Same
		// guard the hand binder takes before writing psp.Sprite.
		mAnchorSpr = Actor.GetSpriteIndex("SHOT");

		// Primed, not zeroed: the first WorldTick then runs a full
		// Discover+Rebind immediately. Our WorldLoaded can land BEFORE
		// RS_ForeignModelHandler has scanned, in which case the Discover just
		// below answers "no model" for everything and the tic-1 pass is what
		// actually binds. Zeroing here would leave a second of bare sprites.
		mSweep = SWEEP_TICS;
		mWasEnabled = Enabled();
		if (mWasEnabled) Discover();

		// The zoo map fills itself. Keyed on the map NAME rather than on a
		// thing placed in it, so maps/MSZOO.wad needs no DoomEdNum and cannot
		// collide with the editor numbers of whatever mod is loaded next to
		// us. Runs whether or not pickups are enabled -- the zoo spawns the
		// display classes directly and does not go through the binder at all,
		// which is exactly what makes it useful for judging the MODELDEF
		// numbers in isolation.
		if (level.MapName.MakeUpper() == "MSZOO" &&
		    consoleplayer >= 0 && consoleplayer < MAXPLAYERS && playeringame[consoleplayer])
		{
			SpawnZoo(players[consoleplayer].mo);
		}
	}

	override void WorldThingSpawned(WorldEvent e)
	{
		if (!Enabled() || mAnchorSpr < 0) return;
		let w = Weapon(e.Thing);
		if (!w || w.Owner) return;
		Track(w);
	}

	override void WorldTick()
	{
		bool on = Enabled();
		if (!on)
		{
			if (mWasEnabled) { ReleaseAll(); mWasEnabled = false; }
			return;
		}
		if (!mWasEnabled) { mWasEnabled = true; mSweep = SWEEP_TICS; }
		if (mAnchorSpr < 0) return;

		// Per tic: the cheap half. Drop anything dead or picked up, and
		// re-pin a sprite their own state machine has moved. Compare before
		// writing so the common single-frame pickup costs one int compare.
		for (int i = mBinds.Size() - 1; i >= 0; --i)
		{
			let b = mBinds[i];
			if (!b || !b.item || b.item.Owner) { mBinds.Delete(i); continue; }
			if (b.bound == "") continue;
			if (b.item.sprite != mAnchorSpr) b.item.sprite = mAnchorSpr;
			if (b.item.frame  != 0)          b.item.frame  = 0;
		}

		if (++mSweep < SWEEP_TICS) return;
		mSweep = 0;
		Discover();
		Rebind();
	}

	// Find floor weapons we are not already tracking.
	//
	// A periodic sweep and not just WorldThingSpawned, because a weapon can
	// re-enter the world without being spawned: DropInventory hands the
	// SAME actor back to the map, and no spawn event fires for it. The
	// event is still worth having -- it binds a monster's dropped weapon
	// immediately instead of up to a second later.
	void Discover()
	{
		let it = ThinkerIterator.Create("Weapon");
		Actor a;
		while (a = Actor(it.Next()))
		{
			let w = Weapon(a);
			if (!w || w.Owner) continue;
			Track(w);
		}
	}

	void Track(Weapon w)
	{
		for (int i = 0; i < mBinds.Size(); ++i)
			if (mBinds[i] && mBinds[i].item == w) return;

		let b = new("MS_PickupBind");
		b.item       = w;
		b.origSprite = w.sprite;
		b.origFrame  = w.frame;
		b.bound      = "";
		mBinds.Push(b);
		ApplyTo(b);
	}

	// Which pickup model this item should be wearing, or "" for none.
	//
	// Reads the hand binder's answer rather than re-deriving one: same
	// entry, same archetype, same modelPick1. If they disagreed, the gun on
	// the floor would not be the gun you picked up, which is the entire
	// point of the feature.
	string WantFor(Weapon w)
	{
		let h = RS_ForeignModelHandler.Get();
		if (!h || !h.mShelf || !mPU) return "";
		if (RS_ForeignModelHandler.CannotFire(w.GetClass())) return "";

		int idx = h.FindEntry(w.GetClassName());
		if (idx < 0) return "";
		let en = h.mEntries[idx];

		string mcls, anchor; int heldFrame, restFrame, frameCount;
		if (!h.mShelf.Get(en.archetype, en.modelPick1, mcls, anchor, heldFrame, restFrame, frameCount))
			return "";

		return mPU.PickupFor(mcls);
	}

	void ApplyTo(MS_PickupBind b)
	{
		if (!b || !b.item) return;
		let w = b.item;

		string want = WantFor(w);
		if (want == "")
		{
			// No model for this donor. Hand the item back rather than
			// leaving it pinned to an anchor nothing resolves -- that is
			// the one way this file could make something LOOK broken
			// instead of merely unchanged.
			if (b.bound != "") Release(b);
			return;
		}
		if (b.bound == want) return;

		w.A_ChangeModel(want);
		w.sprite = mAnchorSpr;
		w.frame  = 0;
		b.bound  = want;
	}

	// Re-solve every tracked item. Cheap because the list is map weapons,
	// not all actors, and it only runs on the sweep.
	void Rebind()
	{
		for (int i = 0; i < mBinds.Size(); ++i)
			if (mBinds[i]) ApplyTo(mBinds[i]);
	}

	// Undo one item: drop our modeldef override and give the sprite back.
	// A_ChangeModel with an empty name is the documented clear (NAME_None).
	void Release(MS_PickupBind b)
	{
		if (!b || !b.item) return;
		if (b.bound != "")
		{
			b.item.A_ChangeModel("");
			b.item.sprite = b.origSprite;
			b.item.frame  = b.origFrame;
			b.bound = "";
		}
	}

	void ReleaseAll()
	{
		for (int i = 0; i < mBinds.Size(); ++i) Release(mBinds[i]);
		mBinds.Clear();
	}

	// -----------------------------------------------------------------
	// THE MODEL ZOO. Spawns one of every pickup model in a grid in front
	// of the player, for looking at all 44 at once.
	//
	// Spawns the MS_PU_* display actors, NOT real weapons: a Weapon in the
	// world runs its own BeginPlay, can be picked up, and in a mod that
	// tracks its arsenal would count as loot appearing from nowhere. The
	// display class resolves the same MODELDEF block through its own class
	// rather than through A_ChangeModel, so what the zoo shows is the block
	// itself -- if a gun is wrong here, the generated numbers are wrong,
	// with no binder in between to blame.
	// -----------------------------------------------------------------
	void SpawnZoo(PlayerPawn pawn)
	{
		if (!pawn) return;
		if (!mPU) { mPU = new("MS_PickupShelf"); mPU.Build(); }

		Array<string> all;
		mPU.AllPickups(all);

		// Clear a previous zoo first, so repeated calls do not stack models on
		// top of each other. Collected first and destroyed after: Destroy()
		// unlinks the thinker the iterator is standing on.
		Array<Actor> stale;
		let it = ThinkerIterator.Create("MS_PickupModel");
		Actor old;
		while (old = Actor(it.Next())) stale.Push(old);
		for (int i = 0; i < stale.Size(); ++i)
			if (stale[i]) stale[i].Destroy();

		// A grid laid out in front of the player, rows receding away.
		// COLS x SPACING is sized so 44 models fit in a normal room without
		// overlapping the widest of them (the minigun, 18 units across).
		int    cols    = 8;
		double spacing = 40.0;
		double first   = 80.0;
		double ang     = pawn.Angle;
		double cs      = cos(ang), sn = sin(ang);

		int made = 0;
		for (int i = 0; i < all.Size(); ++i)
		{
			class<Actor> cls = all[i];
			if (!cls) { Console.Printf("[MS zoo] unknown class %s", all[i]); continue; }

			int row = i / cols;
			int col = i % cols;
			double fwd  = first + row * spacing;
			double side = (col - (cols - 1) * 0.5) * spacing;

			// Rotated into the player's facing so the grid appears ahead of
			// them whichever way they are looking.
			Vector3 p = (pawn.Pos.X + fwd * cs - side * sn,
			             pawn.Pos.Y + fwd * sn + side * cs,
			             pawn.Pos.Z);

			// NO_REPLACE: a display prop must not be swappable by whatever
			// mod is loaded next to us.
			let a = Actor.Spawn(cls, p, NO_REPLACE);
			if (!a) { Console.Printf("[MS zoo] could not spawn %s", all[i]); continue; }

			// Rest it on whatever floor is actually under it -- the grid can
			// easily reach past a step -- and turn it broadside to the
			// player, which is the view that shows a gun's silhouette.
			a.SetZ(a.floorz);
			a.Angle = ang + 90;
			made++;
		}
		Console.Printf("[MS zoo] %d of %d pickup models spawned", made, all.Size());
	}

	override void NetworkProcess(ConsoleEvent e)
	{
		if (e.Name != "ms_modelzoo") return;
		if (e.Player < 0 || e.Player >= MAXPLAYERS || !playeringame[e.Player]) return;
		SpawnZoo(players[e.Player].mo);
	}
}
