"""Build a VR patch for Project Brutality 0.4.1: guns work in either hand, and
their casings, smoke and muzzle sparks come off the gun instead of your face.

    python tools_make_pb_offhand_patch.py [PB zip or folder] [output.pk3]

Load order: Project Brutality, then this patch, then ModelSwapper. The patch
must come after PB; its position relative to ModelSwapper does not matter.

WHY, PART ONE: THE CRASH. A VR engine can move a weapon between hands. It
empties the main hand first, and PB's weapon code asks for the main-hand
sprite layer everywhere -- GetPSprite(PSP_WEAPON) -- which the engine answers
with null for an empty hand. Eleven of PB's lookups use that answer without
checking, so a gun moving to the off hand sometimes crashed the game.

WHY, PART TWO: THE EFFECTS. PB builds its casings, gun smoke and muzzle
sparks at the EYE -- (pos.xy, player.viewz), turned by the head -- plus
desktop screen fudges for FOV, pitch and weapon bob. On a monitor the gun is
drawn at the eye, so that lands on the gun. In a headset the gun is in your
hand and every one of those comes out of your face, whichever hand fires.

WHAT IT CHANGES. One file, zscript/Weapons/BaseWeapon_Functions.zsc:
  - helpers on PB_WeaponBase: the sprite layer of the hand the gun is in,
    and, when VR is driving the attack, that hand's position, aim, and how
    far past it the muzzle sits
  - the eleven unguarded layer lookups rewritten to use them, or null-checked
  - PB_SpawnCasing, PB_GunSmokeSpawn, _SpawnMuzzleSparks and
    _SpawnMuzzleSparksSG build from the hand when VR is driving: smoke and
    sparks at the muzzle, casings at the ejection port a third of the way
    along, each keeping PB's own side and up offsets and PB's own ejection
    velocity, turned by the hand. Without VR the original code runs unchanged.
Nothing else in PB is touched. Its weapon states' direct A_FireCustomMissile
smoke already launches from the hand on a VR engine.

MUZZLE DISTANCE. Barrel length varies a lot. With ModelSwapper loaded, the
patch asks its RS_WeaponArchetypeService -- found by name, so there is no
compile-time link either way -- for "weapon.muzzle.hand", ModelSwapper's
per-family figure. Without it, an average barrel of 18 units is assumed.

HOW IT WORKS WITHOUT AN ENGINE CHANGE. A later archive can replace a mod's
included script file by carrying the same full path -- the engine resolves an
#include to the last file loaded with that name (zcc_parser.cpp) and only
refuses when a mod overrides the engine's own core scripts. So the patch is
that one file, rewritten, and PB's own ZSCRIPT.zc picks it up. It runs on
QuestZDoom exactly as on this fork.

WHY GENERATED, NOT COMMITTED. The file is PB's code. This script reads it out
of your own copy of PB and edits it there, so no PB source lives in this repo.
It refuses any file but PB 0.4.1's, by hash, and every edit must match an
exact number of times -- a different PB fails loudly instead of half-patching.
"""
import hashlib
import os
import re
import sys
import zipfile

PB_FILE = "zscript/Weapons/BaseWeapon_Functions.zsc"
PB_041_SHA1 = "f0ab0ba83babbc610c8633e1cbabce0108b70d81"
DEFAULT_PB = r"E:\oldshit\Project_Brutality-0.4.1\Project_Brutality-0.4.1.zip"
DEFAULT_OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "PB-0.4.1-VR-Offhand-Patch.pk3")

HELPERS = """
	// ---------------------------------------------------------------------
	// VR PATCH -- generated by ModelSwapper's tools_make_pb_offhand_patch.py
	// from Project Brutality 0.4.1.
	//
	// A VR engine can hold this weapon in either hand. PB asked for
	// PSP_WEAPON, the main-hand layer, which belongs to the other hand
	// there -- or, while that hand is empty, comes back null and crashed
	// the game. These read the layer of the hand the gun is actually in.
	// ---------------------------------------------------------------------
	action int PB_VR_HandLayer()
	{
		return invoker.bOffhandWeapon ? PSP_OFFHANDWEAPON : PSP_WEAPON;
	}

	action State PB_VR_HandState()
	{
		let o = invoker.owner;
		if (!o || !o.player) return null;
		let psp = o.player.FindPSprite(invoker.bOffhandWeapon ? PSP_OFFHANDWEAPON : PSP_WEAPON);
		return psp ? psp.CurState : null;
	}

	action State PB_VR_LayerState(int layer)
	{
		let o = invoker.owner;
		if (!o || !o.player) return null;
		let psp = o.player.FindPSprite(layer);
		return psp ? psp.CurState : null;
	}

	// WHERE EFFECTS COME FROM IN VR. PB built casings, smoke and sparks at
	// the eye, which in a headset is your face. When VR is driving the
	// attack they come from the hand holding this gun instead, turned by
	// that hand's aim -- the same fields and conversion the engine uses for
	// A_FireCustomMissile from a hand.
	action bool PB_VR_EffectsFromHand()
	{
		let o = invoker.owner;
		return o && o.player && o.player.mo && o.player.mo.OverrideAttackPosDir;
	}

	action vector3 PB_VR_HandPos()
	{
		let pmo = invoker.owner.player.mo;
		return invoker.bOffhandWeapon ? pmo.OffhandPos : pmo.AttackPos;
	}

	action vector3 PB_VR_HandAngles()
	{
		let pmo = invoker.owner.player.mo;
		if (invoker.bOffhandWeapon)
			return (pmo.OffhandAngle + 90, -pmo.OffhandPitch, -pmo.OffhandRoll);
		return (pmo.AttackAngle + 90, -pmo.AttackPitch, -pmo.AttackRoll);
	}

	// How far past the hand the muzzle sits. ModelSwapper knows each weapon
	// family's barrel length and answers by name through its service, so
	// this patch never names it; without ModelSwapper, an average barrel.
	action double PB_VR_MuzzleDistance()
	{
		let it = ServiceIterator.Find("RS_WeaponArchetypeService");
		let svc = it.Next();
		if (svc)
		{
			string d = svc.GetString("weapon.muzzle.hand", "", invoker.bOffhandWeapon ? 1 : 0);
			if (d.Length() > 0 && d.ToDouble() > 0) return d.ToDouble();
		}
		return 18;
	}
"""

# Declarations for the two muzzle-spark loops: the VR frame, once per call.
SPARK_DECL_OLD = "        vector3 spos, svel, randvel;\n"
SPARK_DECL_NEW = """        vector3 spos, svel, randvel;
        bool vr = PB_VR_EffectsFromHand();
        vector3 handPos, handAng;
        double muzzle = 0;
        if (vr) { handPos = PB_VR_HandPos(); handAng = PB_VR_HandAngles(); muzzle = PB_VR_MuzzleDistance(); }
"""

# _SpawnMuzzleSparks. d2 arrives with PB's +15 and d3 with its -10.5 from
# PB_MuzzleFlashEffects -- the eye-to-screen-gun offsets -- so VR undoes those.
SPARKS_OLD = ("            spos = PB_Math.RelativeToGlobalCoords((self.pos.xy, self.player.viewz), (self.angle + angleOfs, self.pitch, self.roll), (self.radius + d2 - (5.0 * abs(sin(self.pitch))) + fovOfs, -d1, d3) + randvel, true);\n"
              "\t\t    svel = PB_Math.RelativeToGlobalCoords((0, 0, 0), (self.angle + angleOfs, self.pitch, self.roll), randvel + (7, 0, 0));\n")
SPARKS_NEW = """            if (vr)
            {
                spos = PB_Math.RelativeToGlobalCoords(handPos, (handAng.x + angleOfs, handAng.y, handAng.z), (muzzle + max(0., d2 - 15), -d1, d3 + 10.5) + randvel, true);
                svel = PB_Math.RelativeToGlobalCoords((0, 0, 0), (handAng.x + angleOfs, handAng.y, handAng.z), randvel + (7, 0, 0));
            }
            else
            {
""" + SPARKS_OLD + """            }
"""

SPARKS_SG_OLD = ("            spos = PB_Math.RelativeToGlobalCoords((self.pos.xy, self.player.viewz), (self.angle + angleOfs, self.pitch, self.roll), (self.radius + d2 - (5.0 * abs(sin(self.pitch))) + fovOfs, -d1, d3) + (0, randvel.y, randvel.z), true);\n"
                 "\t\t    svel = PB_Math.RelativeToGlobalCoords((0, 0, 0), (self.angle + angleOfs, self.pitch, self.roll), randvel);\n")
SPARKS_SG_NEW = """            if (vr)
            {
                spos = PB_Math.RelativeToGlobalCoords(handPos, (handAng.x + angleOfs, handAng.y, handAng.z), (muzzle + max(0., d2 - 15), -d1, d3 + 10.5) + (0, randvel.y, randvel.z), true);
                svel = PB_Math.RelativeToGlobalCoords((0, 0, 0), (handAng.x + angleOfs, handAng.y, handAng.z), randvel);
            }
            else
            {
""" + SPARKS_SG_OLD + """            }
"""

# PB_GunSmokeSpawn. ofs already carries PB's +15 forward and -10.5 down.
SMOKE_OLD = ("\t\tVector3 spos = PB_Math.RelativeToGlobalCoords((self.pos.xy, self.player.viewz), (self.angle, self.pitch, self.roll), (self.radius + ofs.y - (5.0 * abs(sin(self.pitch))) + fovOfs, -ofs.x, ofs.z), true);\n"
             "\t\tVector3 svel = PB_Math.RelativeToGlobalCoords((self.vel.xy, 0), (self.angle, self.pitch, self.roll), vofs);\n")
SMOKE_NEW = """\t\tVector3 spos, svel;
\t\tif (PB_VR_EffectsFromHand())
\t\t{
\t\t\tvector3 handAng = PB_VR_HandAngles();
\t\t\tspos = PB_Math.RelativeToGlobalCoords(PB_VR_HandPos(), handAng, (PB_VR_MuzzleDistance() + max(0., ofs.y - 15), -ofs.x, ofs.z + 10.5), true);
\t\t\tsvel = PB_Math.RelativeToGlobalCoords((self.vel.xy, 0), handAng, vofs);
\t\t}
\t\telse
\t\t{
\t\t\tspos = PB_Math.RelativeToGlobalCoords((self.pos.xy, self.player.viewz), (self.angle, self.pitch, self.roll), (self.radius + ofs.y - (5.0 * abs(sin(self.pitch))) + fovOfs, -ofs.x, ofs.z), true);
\t\t\tsvel = PB_Math.RelativeToGlobalCoords((self.vel.xy, 0), (self.angle, self.pitch, self.roll), vofs);
\t\t}
"""

# PB_SpawnCasing. PB's forward/up offsets place the ejection port on its
# screen gun relative to the eye; in VR the port is on the gun in the hand,
# so only PB's side offset (scaled down) and its ejection velocity carry over.
CASING_OLD = ("\t\tVector3 spos = PB_Math.RelativeToGlobalCoords((self.pos.xy, self.player.viewz), (self.angle, self.pitch, self.roll), (xOfs - (5.0 * abs(sin(self.pitch))) + fovOfs, horOfs, vertOfs), true);\n"
              "\t\tVector3 svel = PB_Math.RelativeToGlobalCoords((self.vel.xy, 0), (self.angle, self.pitch, self.roll), (xSpeed, horSpeed, vertSpeed));\n")
CASING_NEW = """\t\tbool vr = PB_VR_EffectsFromHand();
\t\tvector3 handPos, handAng;
\t\tdouble portFwd = 0;
\t\tif (vr) { handPos = PB_VR_HandPos(); handAng = PB_VR_HandAngles(); portFwd = PB_VR_MuzzleDistance() * 0.35; }
\t\tVector3 spos, svel;
\t\tif (vr)
\t\t{
\t\t\tspos = PB_Math.RelativeToGlobalCoords(handPos, handAng, (portFwd, horOfs * 0.25, 2.5), true);
\t\t\tsvel = PB_Math.RelativeToGlobalCoords((self.vel.xy, 0), handAng, (xSpeed, horSpeed, vertSpeed));
\t\t}
\t\telse
\t\t{
\t\t\tspos = PB_Math.RelativeToGlobalCoords((self.pos.xy, self.player.viewz), (self.angle, self.pitch, self.roll), (xOfs - (5.0 * abs(sin(self.pitch))) + fovOfs, horOfs, vertOfs), true);
\t\t\tsvel = PB_Math.RelativeToGlobalCoords((self.vel.xy, 0), (self.angle, self.pitch, self.roll), (xSpeed, horSpeed, vertSpeed));
\t\t}
"""

CASING_ANGLE_OLD = "\t\t\tpCase.angle = self.angle;\n"
CASING_ANGLE_NEW = "\t\t\tpCase.angle = vr ? handAng.x : self.angle;\n"

CASING_SPARK_OLD = ("                    spos = PB_Math.RelativeToGlobalCoords((self.pos.xy, self.player.viewz), (self.angle, self.pitch, self.roll), (xOfs - (5.0 * abs(sin(self.pitch))) + fovOfs, horOfs, vertOfs) + randvel, true);\n"
                    "                    svel = PB_Math.RelativeToGlobalCoords((self.vel.xy, 0), (self.angle, self.pitch, self.roll), (xSpeed, horSpeed, vertSpeed) + randvel);\n")
CASING_SPARK_NEW = """                    if (vr)
                    {
                        spos = PB_Math.RelativeToGlobalCoords(handPos, handAng, (portFwd, horOfs * 0.25, 2.5) + randvel, true);
                        svel = PB_Math.RelativeToGlobalCoords((self.vel.xy, 0), handAng, (xSpeed, horSpeed, vertSpeed) + randvel);
                    }
                    else
                    {
""" + CASING_SPARK_OLD + """                    }
"""

README = """PB-0.4.1-VR-Offhand-Patch
=========================

A VR patch for Project Brutality 0.4.1:
  - guns move between hands without crashing
  - casings, gun smoke and muzzle sparks come off the gun in whichever hand
    holds it, instead of out of your face

Load order: Project Brutality 0.4.1, then this patch, then ModelSwapper.

It replaces one PB script file, zscript/Weapons/BaseWeapon_Functions.zsc.
Without VR, PB's original code runs unchanged. Built by ModelSwapper's
tools_make_pb_offhand_patch.py from your own copy of PB; for PB 0.4.1 only.
"""


def fail(msg):
    print("REFUSED: " + msg)
    sys.exit(1)


def read_pb_file(src):
    if os.path.isdir(src):
        p = os.path.join(src, *PB_FILE.split("/"))
        if not os.path.isfile(p):
            fail("no %s under %s" % (PB_FILE, src))
        return open(p, "rb").read()
    z = zipfile.ZipFile(src)
    names = [n for n in z.namelist() if n.lower() == PB_FILE.lower()]
    if not names:
        fail("no %s inside %s" % (PB_FILE, src))
    return z.read(names[0])


def sub_exact(text, pattern, repl, count, what, flags=0):
    new, n = re.subn(pattern, repl, text, flags=flags)
    if n != count:
        fail("%s: expected %d match(es), found %d -- not PB 0.4.1's file?" % (what, count, n))
    return new


def replace_exact(text, old, new, count, what):
    n = text.count(old)
    if n != count:
        fail("%s: expected %d match(es), found %d -- not PB 0.4.1's file?" % (what, count, n))
    return text.replace(old, new)


def main():
    args = sys.argv[1:]
    src = args[0] if len(args) > 0 else DEFAULT_PB
    out = args[1] if len(args) > 1 else DEFAULT_OUT

    raw = read_pb_file(src)
    sha = hashlib.sha1(raw).hexdigest()
    if sha != PB_041_SHA1:
        fail("%s is not Project Brutality 0.4.1's (sha1 %s, expected %s)" % (PB_FILE, sha, PB_041_SHA1))
    text = raw.decode("latin-1")

    # 1. helpers, first thing inside the class
    text = sub_exact(text, r"\Aextend class PB_WeaponBase\n\{\n",
                     lambda m: m.group(0) + HELPERS + "\n", 1, "class header")

    # 2. the four identical main-hand state reads (kick checks, ready, sliding)
    text = replace_exact(text, "invoker.owner.player.GetPSprite(PSP_WEAPON).Curstate",
                         "PB_VR_HandState()", 4, "main-hand state reads")

    # 3. the dual-wield idle overlays, layers 10 and 11
    for layer in (10, 11):
        text = replace_exact(text, "invoker.owner.player.GetPSprite(%d).Curstate" % layer,
                             "PB_VR_LayerState(%d)" % layer, 1, "overlay %d state read" % layer)

    # 4. the empty-magazine check
    text = replace_exact(text, "InStateSequence(player.GetPSprite(PSP_WEAPON).Curstate,",
                         "InStateSequence(PB_VR_HandState(),", 1, "gun-empty check")

    # 5. the three sprite writes
    text = sub_exact(text,
                     r"(action void A_SetOverlaySprite\(int layer, String str\)\s*\{\s*let psp = player\.GetPSprite\(layer\);\s*)psp\.sprite = GetSpriteIndex\(str\);",
                     r"\1if (psp) psp.sprite = GetSpriteIndex(str);", 1, "A_SetOverlaySprite")
    text = sub_exact(text,
                     r"(action void A_SetWeaponSprite\(String str\)\s*\{\s*)let psp = player\.GetPSprite\(PSP_WEAPON\);((?:\s*//[^\n]*)?\s*)psp\.sprite = GetSpriteIndex\(str\);",
                     r"\1let psp = player.GetPSprite(PB_VR_HandLayer());\2if (psp) psp.sprite = GetSpriteIndex(str);",
                     1, "A_SetWeaponSprite")
    text = sub_exact(text,
                     r"(action void A_SetFlashWeaponSprite\(String str\)\s*\{\s*let psp = player\.GetPSprite\(PSP_FLASH\);\s*)psp\.sprite = GetSpriteIndex\(str\);",
                     r"\1if (psp) psp.sprite = GetSpriteIndex(str);", 1, "A_SetFlashWeaponSprite")

    # 6. casings, smoke and sparks from the hand in VR
    text = replace_exact(text, SPARKS_OLD, SPARKS_NEW, 1, "_SpawnMuzzleSparks origin")
    text = replace_exact(text, SPARKS_SG_OLD, SPARKS_SG_NEW, 1, "_SpawnMuzzleSparksSG origin")
    text = replace_exact(text, SPARK_DECL_OLD, SPARK_DECL_NEW, 2, "muzzle-spark declarations")
    text = replace_exact(text, SMOKE_OLD, SMOKE_NEW, 1, "PB_GunSmokeSpawn origin")
    text = replace_exact(text, CASING_OLD, CASING_NEW, 1, "PB_SpawnCasing origin")
    text = replace_exact(text, CASING_ANGLE_OLD, CASING_ANGLE_NEW, 1, "PB_SpawnCasing casing angle")
    text = replace_exact(text, CASING_SPARK_OLD, CASING_SPARK_NEW, 1, "PB_SpawnCasing spark origin")

    # 7. checks: nothing unguarded left, every eye-built effect has a VR branch
    code = "\n".join(l.split("//")[0] for l in text.splitlines())
    left = re.findall(r"(?:GetPSprite|FindPSprite)\s*\([^)]*\)\s*\.", code)
    if left:
        fail("unguarded lookups remain: %s" % left)
    eye_built = len(re.findall(r"RelativeToGlobalCoords\(\(self\.pos\.xy, self\.player\.viewz\)", code))
    hand_built = len(re.findall(r"RelativeToGlobalCoords\((handPos|PB_VR_HandPos\(\))", code))
    if eye_built != 5 or hand_built != 5:
        fail("expected 5 eye-built effect origins each with a hand-built twin, found %d eye / %d hand" % (eye_built, hand_built))
    if "PSP_OFFHANDWEAPON" not in text:
        fail("patched file does not mention the off hand")

    header = ("// Project Brutality 0.4.1 -- VR PATCH. Generated by ModelSwapper's\n"
              "// tools_make_pb_offhand_patch.py from the player's own copy of PB.\n"
              "// Replaces this file of PB when loaded after it. See PB_VR_HandLayer below.\n")
    data = (header + text).encode("latin-1")

    with zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED) as z:
        z.writestr(PB_FILE, data)
        z.writestr("PB-VR-OFFHAND-PATCH.txt", README)
    print("wrote %s (%d bytes): %s patched -- 11 lookups hand-aware or null-safe, "
          "casings, smoke and sparks built from the hand in VR" % (out, os.path.getsize(out), PB_FILE))
    return 0


if __name__ == "__main__":
    sys.exit(main())
