"""Build a patch that lets Project Brutality 0.4.1's guns work in the VR off hand.

    python tools_make_pb_offhand_patch.py [PB zip or folder] [output.pk3]

Load order: Project Brutality, then this patch, then ModelSwapper. The patch
must come after PB; its position relative to ModelSwapper does not matter.

WHY. A VR engine can move a weapon to the off hand. It empties the main hand
first, and PB's weapon code asks for the main-hand sprite layer everywhere --
GetPSprite(PSP_WEAPON) -- which the engine answers with null for an empty
hand. Eleven of PB's lookups use that answer without checking, so an off-hand
PB gun crashes the game whenever one of them runs while the main hand is
empty: always during the swap itself, and later if the main hand stays empty.

WHAT IT CHANGES. One file, zscript/Weapons/BaseWeapon_Functions.zsc:
  - three helpers on PB_WeaponBase that read the layer of the hand the gun is
    actually in, returning null instead of crashing
  - the eleven unguarded lookups rewritten to use them, or given a null check
Nothing else in PB is touched; every other lookup already checks for null.

HOW IT WORKS WITHOUT AN ENGINE CHANGE. A later archive can replace a mod's
included script file by carrying the same full path -- the engine resolves an
#include to the last file loaded with that name (zcc_parser.cpp) and only
refuses when a mod overrides the engine's own core scripts. So the patch is
that one file, rewritten, and PB's own ZSCRIPT.zc picks it up. It runs on
QuestZDoom exactly as on this fork.

WHY GENERATED, NOT COMMITTED. The file is PB's code. This script reads it out
of your own copy of PB and edits it there, so no PB source lives in this repo.
It refuses any file but PB 0.4.1's, by hash, and every edit must match an
exact number of times -- a different PB fails loudly instead of half-patching.
"""
import hashlib
import io
import os
import re
import sys
import zipfile

PB_FILE = "zscript/Weapons/BaseWeapon_Functions.zsc"
PB_041_SHA1 = "f0ab0ba83babbc610c8633e1cbabce0108b70d81"
DEFAULT_PB = r"E:\oldshit\Project_Brutality-0.4.1\Project_Brutality-0.4.1.zip"
DEFAULT_OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "PB-0.4.1-VR-Offhand-Patch.pk3")

HELPERS = """
	// ---------------------------------------------------------------------
	// VR OFF-HAND PATCH -- generated by ModelSwapper's
	// tools_make_pb_offhand_patch.py from Project Brutality 0.4.1.
	//
	// A VR engine can hold this weapon in the off hand. PB asked for
	// PSP_WEAPON, the main-hand layer, which belongs to the other hand
	// there -- or, while that hand is empty, comes back null and crashed
	// the game. These read the layer of the hand the gun is actually in.
	// ---------------------------------------------------------------------
	action int PB_VR_HandLayer()
	{
		return invoker.bOffhandWeapon ? PSP_OFFHANDWEAPON : PSP_WEAPON;
	}

	action State PB_VR_HandState()
	{
		let o = invoker.owner;
		if (!o || !o.player) return null;
		let psp = o.player.FindPSprite(invoker.bOffhandWeapon ? PSP_OFFHANDWEAPON : PSP_WEAPON);
		return psp ? psp.CurState : null;
	}

	action State PB_VR_LayerState(int layer)
	{
		let o = invoker.owner;
		if (!o || !o.player) return null;
		let psp = o.player.FindPSprite(layer);
		return psp ? psp.CurState : null;
	}
"""

README = """PB-0.4.1-VR-Offhand-Patch
=========================

Lets Project Brutality 0.4.1's guns work in the VR off hand without crashing.

Load order: Project Brutality 0.4.1, then this patch, then ModelSwapper.

It replaces one PB script file, zscript/Weapons/BaseWeapon_Functions.zsc,
with a copy whose main-hand-only sprite layer lookups ask for the hand the
gun is in and check for null. Built by ModelSwapper's
tools_make_pb_offhand_patch.py from your own copy of PB; for PB 0.4.1 only.
"""


def fail(msg):
    print("REFUSED: " + msg)
    sys.exit(1)


def read_pb_file(src):
    if os.path.isdir(src):
        p = os.path.join(src, *PB_FILE.split("/"))
        if not os.path.isfile(p):
            fail("no %s under %s" % (PB_FILE, src))
        return open(p, "rb").read()
    z = zipfile.ZipFile(src)
    names = [n for n in z.namelist() if n.lower() == PB_FILE.lower()]
    if not names:
        fail("no %s inside %s" % (PB_FILE, src))
    return z.read(names[0])


def sub_exact(text, pattern, repl, count, what, flags=0):
    new, n = re.subn(pattern, repl, text, flags=flags)
    if n != count:
        fail("%s: expected %d match(es), found %d -- not PB 0.4.1's file?" % (what, count, n))
    return new


def main():
    args = sys.argv[1:]
    src = args[0] if len(args) > 0 else DEFAULT_PB
    out = args[1] if len(args) > 1 else DEFAULT_OUT

    raw = read_pb_file(src)
    sha = hashlib.sha1(raw).hexdigest()
    if sha != PB_041_SHA1:
        fail("%s is not Project Brutality 0.4.1's (sha1 %s, expected %s)" % (PB_FILE, sha, PB_041_SHA1))
    text = raw.decode("latin-1")

    # 1. helpers, first thing inside the class
    text = sub_exact(text, r"\Aextend class PB_WeaponBase\n\{\n",
                     lambda m: m.group(0) + HELPERS + "\n", 1, "class header")

    # 2. the four identical main-hand state reads (kick checks, ready, sliding)
    text = sub_exact(text, re.escape("invoker.owner.player.GetPSprite(PSP_WEAPON).Curstate"),
                     "PB_VR_HandState()", 4, "main-hand state reads")

    # 3. the dual-wield idle overlays, layers 10 and 11
    for layer in (10, 11):
        text = sub_exact(text, re.escape("invoker.owner.player.GetPSprite(%d).Curstate" % layer),
                         "PB_VR_LayerState(%d)" % layer, 1, "overlay %d state read" % layer)

    # 4. the empty-magazine check
    text = sub_exact(text, re.escape("InStateSequence(player.GetPSprite(PSP_WEAPON).Curstate,"),
                     "InStateSequence(PB_VR_HandState(),", 1, "gun-empty check")

    # 5. the three sprite writes
    text = sub_exact(text,
                     r"(action void A_SetOverlaySprite\(int layer, String str\)\s*\{\s*let psp = player\.GetPSprite\(layer\);\s*)psp\.sprite = GetSpriteIndex\(str\);",
                     r"\1if (psp) psp.sprite = GetSpriteIndex(str);", 1, "A_SetOverlaySprite")
    text = sub_exact(text,
                     r"(action void A_SetWeaponSprite\(String str\)\s*\{\s*)let psp = player\.GetPSprite\(PSP_WEAPON\);((?:\s*//[^\n]*)?\s*)psp\.sprite = GetSpriteIndex\(str\);",
                     r"\1let psp = player.GetPSprite(PB_VR_HandLayer());\2if (psp) psp.sprite = GetSpriteIndex(str);",
                     1, "A_SetWeaponSprite")
    text = sub_exact(text,
                     r"(action void A_SetFlashWeaponSprite\(String str\)\s*\{\s*let psp = player\.GetPSprite\(PSP_FLASH\);\s*)psp\.sprite = GetSpriteIndex\(str\);",
                     r"\1if (psp) psp.sprite = GetSpriteIndex(str);", 1, "A_SetFlashWeaponSprite")

    # 6. nothing unguarded left
    code = "\n".join(l.split("//")[0] for l in text.splitlines())
    left = re.findall(r"(?:GetPSprite|FindPSprite)\s*\([^)]*\)\s*\.", code)
    if left:
        fail("unguarded lookups remain: %s" % left)
    if "PSP_OFFHANDWEAPON" not in text:
        fail("patched file does not mention the off hand")

    header = ("// Project Brutality 0.4.1 -- VR OFF-HAND PATCH. Generated by ModelSwapper's\n"
              "// tools_make_pb_offhand_patch.py from the player's own copy of PB.\n"
              "// Replaces this file of PB when loaded after it. See PB_VR_HandLayer below.\n")
    data = (header + text).encode("latin-1")

    with zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED) as z:
        z.writestr(PB_FILE, data)
        z.writestr("PB-VR-OFFHAND-PATCH.txt", README)
    print("wrote %s (%d bytes): %s patched, 11 lookups made hand-aware or null-safe" % (out, os.path.getsize(out), PB_FILE))
    return 0


if __name__ == "__main__":
    sys.exit(main())
